### ISSUE TITLE
Cygwin nearly working but with error

### ISSUE THREAD

**Issue by Quintex49** [socram8888/amiitool#11] opened 2019-07-01 22:18 UTC
$ ./amiitool -e -k retail.bin -i "modified.bin" -o "signed.bin"
Could not open input file: No such file or directory (2)

Do I need to create two bin files in current directory named "modified.bin" and "signed.bin" for amiitool to see them?

**Comment by socram8888** [comment] 2019-07-02 07:52
-i is the input file (which has to exist) and -o is the output file (which will be created). If you don't wanna have them in the amiitool folder, just specify manually the path in those switches (ie "-i /home/marcos/input.bin")

Closing as this is not a bug.

**Closed as completed by socram8888** 2019-07-02 07:52 UTC
